#!/usr/bin/env bash
# transcript.sh — distill a ZCode session rollout log into an Obsidian-friendly
# transcript (user/agent prose per turn; tool calls, thinking, harness noise dropped).
# Full docs: ai/zcode/README.md · main help: --help
set -euo pipefail

# --- configuration presets (override via environment, e.g. HARNESS=OMP transcript.sh) ---
ROLLOUT_DIR="${ROLLOUT_DIR:-$HOME/.zcode/cli/rollout}"
MODEL="${MODEL:-GLM-5.3-Flash}"        # frontmatter model; set empty to derive from the log
PROVIDER="${PROVIDER:-Z.ai}"
HARNESS="${HARNESS:-ZCode}"
ATTACH_MAX_CHARS="${ATTACH_MAX_CHARS:-4000}"   # attached-file content above this is dropped, filename kept

pos=(); noclobber=0; path=""; sess=""; out=""

usage() {
  cat <<'EOF'
transcript.sh — distill a ZCode session rollout log into an Obsidian-friendly transcript

Usage: transcript.sh [--no-clobber] [PATH] [SESSION]
  PATH      where the transcript goes. An existing directory gets an autogenerated
            filename (X.XX.XX.md for a semver-named folder, else the next free
            1.md, 2.md, ...); an existing .md file is overwritten; a new *.md path
            is created when its parent exists; a new extensionless path with a
            slash becomes a directory. Relative paths resolve against the repo
            root first, then the current directory. Default: destination from the
            clipboard (the copied path must already exist), falling back to
            newest session → stdout.
  SESSION   a rollout .jsonl path, or a sess_<uuid> (unique prefix ok); default:
            newest. Arguments are recognized by what they are, so either order
            works: a session id or .jsonl path is a source, .md files and
            directories are destinations.

  -nc, --no-clobber   refuse to overwrite an existing output file

Config (env-overridable presets at the top of the script):
  MODEL, PROVIDER, HARNESS, ROLLOUT_DIR, ATTACH_MAX_CHARS

Full docs: ai/zcode/README.md ("Transcript export")
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -nc|--no-clobber) noclobber=1; shift ;;
    -o|-d) echo "error: $1 was removed — pass the destination as PATH (see --help)" >&2; exit 1 ;;
    -*) echo "error: unknown option: $1" >&2; exit 1 ;;
    *) pos+=("$1"); shift ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"

# clean a clipboard path: first non-empty line, strip CR/surrounding quotes/file://,
# trim whitespace, expand ~ (same stripping rules as ~/.bash/quote-gif.sh)
clean_path() {
  local p input="$1"
  p="$(printf '%s\n' "$input" | grep -m1 -v '^[[:space:]]*$')" || return 1
  p="$(printf '%s' "$p" | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
      -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'$/\1/" -e 's|^file://||' -e 's|/*$||')"
  [[ -n "$p" ]] || return 1
  printf '%s' "${p/#\~/$HOME}"
}

# does this argument name a rollout source? (id/prefix in ROLLOUT_DIR, or an
# existing .jsonl path — transcripts (.md) are destinations, never sources)
is_session() {
  local p="$1"
  [[ -f "$ROLLOUT_DIR/model-io-$p.jsonl" ]] && return 0
  local m=("$ROLLOUT_DIR/model-io-$p"*.jsonl)
  if (( ${#m[@]} == 1 )) && [[ -f "${m[0]}" ]]; then return 0; fi
  local abs="$p"; [[ "$p" != /* ]] && abs="$PWD/$p"
  [[ -f "$abs" && "$abs" == *.jsonl ]] && return 0
  return 1
}

# next transcript filename for a destination dir: X.XX.XX.md for a semver-named
# folder, else the highest existing N.md + 1 (glob iteration, never ls-parsed)
pick_output() {
  local base n=0 f fbase v dir="$1"
  base="$(basename "$dir")"
  if [[ "$base" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf '%s/%s.md' "$dir" "$base"
    return 0
  fi
  for f in "$dir"/*.md; do
    [[ -f "$f" ]] || continue
    fbase="${f##*/}"
    if [[ "$fbase" =~ ^[0-9]+\.md$ ]]; then
      v=$((10#${fbase%.md}))          # 10# keeps 08.md, 09.md from parsing as octal
      if (( v > n )); then n=$v; fi
    fi
  done
  printf '%s/%d.md' "$dir" "$((n + 1))"
}

# resolve PATH → concrete output file. Relative paths try the repo root, then
# the cwd. Existing dirs get an autogenerated name; existing .md files are
# returned verbatim (overwrite is the default; --no-clobber refuses later);
# a new *.md path needs an existing parent; a new extensionless path with a
# slash is created as a directory. With clip=1 (clipboard) nothing is created.
resolve_out() {
  local p="$1" clip="${2:-0}" cand
  local cands=()
  if [[ "$p" == /* ]]; then cands=("$p"); else cands=("$REPO_ROOT/$p" "$PWD/$p"); fi
  for cand in "${cands[@]}"; do
    if [[ -d "$cand" ]]; then pick_output "$cand"; return 0; fi
    if [[ -f "$cand" ]]; then
      if [[ "$cand" == *.md ]]; then printf '%s' "$cand"; return 0; fi
      return 1
    fi
  done
  if (( clip )); then return 1; fi
  for cand in "${cands[@]}"; do
    if [[ "$cand" == *.md && -d "$(dirname "$cand")" ]]; then
      printf '%s' "$cand"; return 0
    fi
  done
  for cand in "${cands[@]}"; do
    if [[ "$p" == */* && -d "$(dirname "$cand")" ]] && mkdir -p "$cand"; then
      pick_output "$cand"; return 0
    fi
  done
  return 1
}

case ${#pos[@]} in
  0) ;;
  1) if is_session "${pos[0]}"; then sess="${pos[0]}"; else path="${pos[0]}"; fi ;;
  2)
    if is_session "${pos[0]}" && is_session "${pos[1]}"; then
      echo "error: both arguments look like rollout sources: ${pos[0]}, ${pos[1]}" >&2; exit 1
    elif is_session "${pos[0]}"; then   # session-first order — accept, swap
      sess="${pos[0]}"; path="${pos[1]}"
    else
      path="${pos[0]}"; sess="${pos[1]}"
    fi ;;
  *) echo "error: too many arguments: ${pos[*]}" >&2; exit 1 ;;
esac

if [[ -z "$sess" ]]; then
  for f in "$ROLLOUT_DIR"/model-io-sess_*.jsonl; do
    if [[ -f "$f" && (-z "$sess" || "$f" -nt "$sess") ]]; then sess="$f"; fi
  done
  [[ -n "$sess" ]] || { echo "error: no model-io-sess_*.jsonl found in $ROLLOUT_DIR" >&2; exit 1; }
elif [[ "$sess" != /* && "$sess" != *.jsonl ]]; then   # session id or unambiguous prefix
  exact="$ROLLOUT_DIR/model-io-$sess.jsonl"
  if [[ -f "$exact" ]]; then
    sess="$exact"
  else
    matches=("$ROLLOUT_DIR/model-io-$sess"*.jsonl)
    if (( ${#matches[@]} == 1 )) && [[ -f "${matches[0]}" ]]; then
      sess="${matches[0]}"
    else
      echo "error: no unique session matching '$sess'" >&2; exit 1
    fi
  fi
fi
if [[ "$sess" != /* ]]; then sess="$PWD/$sess"; fi
[[ -f "$sess" ]] || { echo "error: not a file: $sess" >&2; exit 1; }

# Side-conversation rollouts carry an injected banner as a user message; per
# the docs (zcode.z.ai/en/docs/agents#side-conversation) side conversations
# are deliberately temporary, so they're excluded from transcript exports.
# Role-aware python (a main-session log can quote the banner inside tool
# output), run before the output file is opened so a refusal strands no file.
if python3 - "$sess" <<'PY'
import json, sys
BANNER = "The preceding conversation was inherited from the parent task"
for line in open(sys.argv[1]):
    try:
        rec = json.loads(line)
    except json.JSONDecodeError:
        continue
    if not isinstance(rec, dict):
        continue
    for m in (rec.get("request") or {}).get("messages", []):
        if m.get("role") != "user":
            continue
        c = m.get("content")
        text = c if isinstance(c, str) else (
            "".join(p.get("text", "") for p in c if isinstance(p, dict))
            if isinstance(c, list) else "")
        if text.lstrip().startswith(BANNER):
            sys.exit(0)   # side conversation detected
sys.exit(1)
PY
then
  echo "error: side-conversation rollout, excluded from transcript exports: $sess" >&2
  exit 1
fi

if [[ -n "$path" ]]; then
  out="$(resolve_out "$path")" || { echo "error: cannot resolve output path: $path" >&2; exit 1; }
elif (( ${#pos[@]} == 0 )); then   # double-click mode: dest from clipboard
  clip=""
  if command -v wl-paste >/dev/null 2>&1; then
    clip="$(wl-paste --primary 2>/dev/null || true)"
    [[ -z "$clip" ]] && clip="$(wl-paste 2>/dev/null || true)"
  fi
  if [[ -n "$clip" ]] && p="$(clean_path "$clip")"; then
    out="$(resolve_out "$p" 1)" || out=""
  fi
fi

# overwrite is the default for same-path reruns; --no-clobber restores the refusal
if [[ -n "$out" && $noclobber -eq 1 && -e "$out" ]]; then
  echo "error: output already exists: $out (drop --no-clobber to overwrite)" >&2
  exit 1
fi

prev_file=""
if [[ -n "$out" ]]; then
  if [[ -f "$out" ]]; then
    prev_file="$(mktemp)"
    cp "$out" "$prev_file"
  fi
  echo "transcript.sh: writing to $out" >&2
  exec >"$out"
fi

ROLLOUT_DIR="$ROLLOUT_DIR" MODEL="$MODEL" PROVIDER="$PROVIDER" HARNESS="$HARNESS" \
ATTACH_MAX_CHARS="$ATTACH_MAX_CHARS" python3 - "$sess" "$prev_file" <<'PY'
import json, os, re, sys

path = sys.argv[1]
prev_path = sys.argv[2] if len(sys.argv) > 2 else ""
model_cfg = os.environ["MODEL"]
provider = os.environ["PROVIDER"]
harness = os.environ["HARNESS"]
attach_max = int(os.environ["ATTACH_MAX_CHARS"])

records = []
with open(path) as fh:
    for line in fh:
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            continue
        if rec.get("querySource") != "main_turn":
            continue
        if (rec.get("model") or {}).get("role") == "lite":
            continue
        if not rec.get("turnId") or not isinstance(rec.get("request"), dict):
            continue
        records.append(rec)
if not records:
    sys.exit("error: no main-turn model calls found in " + path)

REMINDER = re.compile(r"(?s)<system-reminder>.*?</system-reminder>\s*")
# Harness-injected background-task notices ride in turn history as bare user
# messages; without stripping, the mid-turn classifier mistakes them for steering.
NOTIFICATION = re.compile(r"(?s)<task-notification>.*?</task-notification>\s*")
CONTINUE_ONLY = re.compile(
    r"^\s*(?:continue(?: from cutoff| from where (?:you|we) left off| working|,? please)?"
    r"|go on|keep going|[.?!]+)[.!?]*\s*$", re.I)
# Auto-compaction injects the prior-context summary as a user message ("This
# session is being continued..."). It duplicates turns already in the log and
# is harness context, not user intent — exclude it entirely (its quoted marker
# syntax also false-matches IMG_SRC, seeding garbage attachments).
CONTINUATION = re.compile(
    r"^This session is being continued from a previous conversation")
ATTACH = re.compile(r"(?s)Contents of (.+?)\s*\n(.*)")
IMG_EXT = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".bmp")
DATA_URI = re.compile(r"!\[[^\]]*\]\(\s*data:[^)]+\)|data:(?:image|application)/[a-z+]+;base64,[A-Za-z0-9+/=]+")
# The harness drops "[Image: source: <path>]" markers into the message text for
# each pasted image; the path is a private local cache, so keep only the filename.
IMG_SRC = re.compile(r"\[Image: source: ([^\]]*)\]")
# GLM server-side tool narration (web_search_prime, analyze_image, ...) is streamed
# into response.text: a call block ("🌐 ... *Executing on server...*") followed by
# "**Output:**" payload paragraphs. Both are tool activity, not agent prose.
SERVER_CALL = re.compile(r"(?s)\*\*🌐 Z\.ai Built-in Tool:[^\n]*\*\*.*?\*Executing on server\.\.\.\*\s*")
SERVER_OUT = re.compile(r"(?ms)^[ \t]*\*\*Output:\*\*[ \t]*\n(?:^[ \t]*\S.*\n)+")

def strip_server_tools(text):
    text = SERVER_CALL.sub("", text)
    text = SERVER_OUT.sub("", text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()

def demote(text):
    """Shift ATX headers down so in-content headers land at ####+ (outside code fences)."""
    out_lines, fence = [], False
    for ln in text.split("\n"):
        if ln.lstrip().startswith("```"):
            fence = not fence
        m = None if fence else re.match(r"^(#{1,6})(\s+)", ln)
        if m:
            lvl = min(max(len(m.group(1)) + 2, 4), 6)
            ln = "#" * lvl + m.group(2) + ln[m.end():]
        out_lines.append(ln)
    return "\n".join(out_lines)

def user_content(msg):
    """Return (typed_text, attached_filenames, content_blocks) for a user message."""
    content = msg.get("content")
    parts = content if isinstance(content, list) else [{"type": "text", "text": str(content)}]
    texts, files, blocks = [], [], []

    def add_file(name):
        if name and name not in files:
            files.append(name)

    for p in parts:
        ptype = p.get("type", "text")
        if ptype == "text":
            raw = p.get("text", "")
        elif ptype in ("image", "file", "document"):
            name = (p.get("filename") or p.get("name") or "").strip()
            add_file(os.path.basename(name) if name else f"{ptype} attachment")
            continue
        else:
            continue
        for block in REMINDER.findall(raw + "\n"):
            m = ATTACH.match(block.strip())
            if m:
                fpath, fcontent = m.group(1).strip(), m.group(2).strip()
                base = os.path.basename(fpath.rstrip("/"))
                if base.lower().endswith(IMG_EXT) or len(fcontent) > attach_max:
                    add_file(base)
                else:
                    blocks.append(f"**{base}:**\n{demote(fcontent)}")
        body = NOTIFICATION.sub("", REMINDER.sub("", raw))
        for m in IMG_SRC.finditer(body):
            add_file(os.path.basename(m.group(1).strip()))
        body = IMG_SRC.sub("", body)
        if DATA_URI.search(body):
            add_file("inline image")
            body = DATA_URI.sub("", body)
        texts.append(re.sub(r"\n{3,}", "\n\n", body).strip())
    # the harness names images via [Image: source:] markers; unnamed typed image
    # parts are the same pictures, so the generic entry is redundant when a
    # named one exists
    if "image attachment" in files and any(f.lower().endswith(IMG_EXT) for f in files):
        files.remove("image attachment")
    typed = "\n\n".join(t for t in texts if t)
    return typed, files, blocks

turns, order = {}, []
for rec in records:
    tid = rec["turnId"]
    if tid not in turns:
        turns[tid] = {"user": None, "steers": [], "files": [], "blocks": [], "seen": None, "agent": []}
        order.append(tid)
    t = turns[tid]
    users = [m for m in rec["request"].get("messages", []) if m.get("role") == "user"]
    typed_users = []
    for msg in users:
        typed, files, blocks = user_content(msg)
        if not typed or CONTINUATION.match(typed):
            continue   # reminder-only, or auto-compaction context
        typed_users.append((typed, files, blocks))
    if t["user"] is None and typed_users:
        t["user"], t["files"], t["blocks"] = typed_users[-1]   # last real user message wins; reminder-only ones skipped
        t["seen"] = {text for text, _, _ in typed_users}
    elif t["seen"]:
        # later model calls of the same turn replay history; a user message that
        # was not in the first call's list was steered in mid-turn
        for text, files, blocks in typed_users:
            if text not in t["seen"]:
                t["seen"].add(text)
                t["steers"].append(text)
                for f in files:
                    if f not in t["files"]:
                        t["files"].append(f)
                t["blocks"].extend(blocks)
    text = (rec.get("response") or {}).get("text") or ""
    if text.strip():
        t["agent"].append(strip_server_tools(text))

# drop continue-only turns, merging their agent output into the interrupted turn
merged = []
for tid in order:
    t = turns[tid]
    if t["user"] is None:
        continue
    if merged and CONTINUE_ONLY.match(t["user"]):
        merged[-1]["agent"].extend(t["agent"])
        continue
    merged.append(t)

if not merged:
    sys.exit("error: no user turns found")

model = model_cfg or next(
    ((r.get("model") or {}).get("modelId") for r in records if (r.get("model") or {}).get("modelId")),
    "unknown")

def render_block(idx, t):
    parts = [f"## Turn {idx}\n\n### User:\n\n", demote(t["user"]), "\n"]
    for s in t["steers"]:
        lines = demote(s).split("\n")
        parts.append("\n" + "\n".join(("> **Steering:** " if j == 0 else "> ") + ln for j, ln in enumerate(lines)) + "\n")
    if t["files"]:
        parts.append("\n**Attachments:**\n")
        for f in t["files"]:
            parts.append(f"`{f}`\n")
    for b in t["blocks"]:
        parts.append("\n" + b + "\n")
    agent = "\n\n".join(demote(a) for a in t["agent"])
    parts.append("\n---\n\n### Agent:\n\n" + (agent if agent else "*(interrupted — no captured agent output)*"))
    return "".join(parts)

frontmatter = "---\n" + f"model: {model}\nprovider: {provider}\nharness: {harness}\n---"
blocks = [render_block(i, t) for i, t in enumerate(merged, 1)]

# The harness prunes rollout logs in place mid-session, so the log can hold
# fewer turns than a previously exported transcript. In that case the log's
# "Turn 1" is NOT the session's first turn: merge instead of overwrite. Log
# turns already covered by the existing transcript (user text matches an
# earlier turn or one of its steering lines) are skipped; if a log turn's user
# text matches the transcript's LAST turn, it is the same turn grown since the
# last export — its not-yet-present agent paragraphs are unioned in; anything
# else is appended with the turn count continuing from the existing transcript.
prev_text = ""
if prev_path and os.path.exists(prev_path):
    prev_text = open(prev_path, encoding="utf-8").read().rstrip("\n")
chunks = re.split(r"(?m)^(?=## Turn \d+\n)", prev_text) if prev_text else None
if chunks is not None and len(chunks) - 1 > len(blocks):
    # Each previously-written chunk (except the last) still ends with the
    # inter-turn "---" separator — strip any trailing hr run from it so the
    # join below adds exactly one (this also cleans up files written by the
    # earlier double-separator bug).
    kept = [re.sub(r"(?:\n+---\n*)+\s*$", "", c).rstrip() for c in chunks[1:]]
    appended = unioned = skipped = 0
    for t in merged:
        if t["user"] and t["user"] in kept[-1]:
            head, sep, agent = kept[-1].partition("\n\n---\n\n### Agent:\n\n")
            if sep:
                paras = agent.split("\n\n")
                before = len(paras)
                for p in "\n\n".join(demote(a) for a in t["agent"]).split("\n\n"):
                    if p not in paras:
                        paras.append(p)
                if len(paras) > before:
                    kept[-1] = head + sep + "\n\n".join(paras)
                    unioned += 1
            continue
        if t["user"] and t["user"] in prev_text:
            skipped += 1
            continue
        kept.append(render_block(len(kept) + 1, t))
        appended += 1
    sys.stdout.write(chunks[0].rstrip("\n") + "\n\n" + "\n\n---\n\n".join(kept) + "\n")
    print(f"note: rollout log holds {len(merged)} turn(s), existing transcript had {len(chunks) - 1} "
          f"(log likely pruned mid-session) — merged: kept {len(chunks) - 1}, "
          f"appended {appended}, grew {unioned} in place, skipped {skipped} already covered",
          file=sys.stderr)
else:
    sys.stdout.write(frontmatter + "\n\n" + "\n\n---\n\n".join(blocks) + "\n")
PY

if [[ -n "$prev_file" ]]; then
  rm -f "$prev_file"
fi

if [[ -n "$out" ]] && command -v notify-send >/dev/null 2>&1; then
  notify-send -a "transcript.sh" "Transcript written" "$out" 2>/dev/null || true
fi
