#!/usr/bin/env bash
# transcript.sh — distill a ZCode session rollout log into an Obsidian-friendly
# transcript (user/agent prose per turn; tool calls, thinking, harness noise dropped).
# Full docs: ai/zcode/README.md · main help: --help · flag help: -o --help, -d --help
set -euo pipefail

# --- configuration presets (override via environment, e.g. HARNESS=OMP transcript.sh) ---
ROLLOUT_DIR="${ROLLOUT_DIR:-$HOME/.zcode/cli/rollout}"
MODEL="${MODEL:-GLM-5.3-Flash}"        # frontmatter model; set empty to derive from the log
PROVIDER="${PROVIDER:-Z.ai}"
HARNESS="${HARNESS:-ZCode}"
ATTACH_MAX_CHARS="${ATTACH_MAX_CHARS:-4000}"   # attached-file content above this is dropped, filename kept

out=""; destdir=""; sess=""; session_given=0

usage() {
  cat <<'EOF'
transcript.sh — distill a ZCode session rollout log into an Obsidian-friendly transcript

Usage: transcript.sh [-o FILE] [-d DIR] [SESSION]
  SESSION   a rollout .jsonl path, or a sess_<uuid> (unique prefix ok); default: newest

  -o FILE   write to FILE (overwrites)
  -d DIR    write into DIR, filename autogenerated: X.XX.XX.md for a semver-named
            folder, else the next free 1.md, 2.md, ...
  no args   destination from the clipboard; falls back to newest session -> stdout

Config (env-overridable presets at the top of the script):
  MODEL, PROVIDER, HARNESS, ROLLOUT_DIR, ATTACH_MAX_CHARS

Flag details:  transcript.sh -o --help | -d --help
Full docs:     ai/zcode/README.md ("Transcript export")
EOF
}

flag_help() {
  local flag="$1"
  if [[ "$flag" == "o" ]]; then
    cat <<'EOF'
-o FILE — write the transcript to FILE
  FILE is used verbatim: no folder resolution, no filename autogeneration, and an
  existing FILE is overwritten (destination-generated names refuse to overwrite).
EOF
  else
    cat <<'EOF'
-d DIR — write into DIR with an autogenerated filename
  X.XX.XX.md when the folder name is semver (the archive/semantic|modular/X.XX.XX
  profile), else the next free 1.md, 2.md, ... — numbering counts only existing
  N.md files, so it jumps past gaps and ignores unrelated files.
  Relative DIR resolves against the repo root first, then the current directory;
  the leaf folder is created if its parent exists. An existing .md file given as
  DIR means "write next to it". A generated name that already exists is refused
  (use -o to overwrite deliberately).
EOF
  fi
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    -o)
      if [[ "${2:-}" == "-h" || "${2:-}" == "--help" ]]; then flag_help o; exit 0; fi
      out="${2:?transcript.sh: -o requires an output file path}"; shift 2 ;;
    -d)
      if [[ "${2:-}" == "-h" || "${2:-}" == "--help" ]]; then flag_help d; exit 0; fi
      destdir="${2:?transcript.sh: -d requires a destination directory}"; shift 2 ;;
    *) sess="$1"; session_given=1; shift ;;
  esac
done

REPO_ROOT="$(cd "$(dirname "$(readlink -f "$0")")/../.." && pwd)"

# clean a clipboard path: first non-empty line, strip CR/surrounding quotes/file://,
# trim whitespace, expand ~ (same stripping rules as ~/.bash/quote-gif.sh)
clean_path() {
  local p input="$1"
  p="$(printf '%s\n' "$input" | grep -m1 -v '^[[:space:]]*$')" || return 1
  p="$(printf '%s' "$p" | tr -d '\r' | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
      -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'$/\1/" -e 's|^file://||' -e 's|/*$||')"
  [[ -n "$p" ]] || return 1
  printf '%s' "${p/#\~/$HOME}"
}

# resolve a destination dir (absolute, or relative to the repo root then cwd).
# An existing .md file means "write next to it". $2=strict lets the leaf dir be
# created when its parent exists; clipboard mode requires it to already exist.
resolve_dest() {
  local p="$1" cand mode="${2:-}"
  if [[ -f "$p" && "$p" == *.md ]]; then p="$(dirname "$p")"; fi
  local cands=()
  if [[ "$p" == /* ]]; then cands=("$p"); else cands=("$REPO_ROOT/$p" "$PWD/$p"); fi
  for cand in "${cands[@]}"; do
    if [[ -d "$cand" ]]; then printf '%s' "$cand"; return 0; fi
    if [[ "$mode" == strict && -d "$(dirname "$cand")" ]] && mkdir -p "$cand"; then
      printf '%s' "$cand"; return 0
    fi
  done
  return 1
}

# next transcript filename for a destination dir: X.XX.XX.md for a semver-named
# folder, else the highest existing N.md + 1 (glob iteration, never ls-parsed)
pick_output() {
  local base n=0 f fbase v dir="$1"
  base="$(basename "$dir")"
  if [[ "$base" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf '%s/%s.md' "$dir" "$base"
    return 0
  fi
  for f in "$dir"/*.md; do
    [[ -f "$f" ]] || continue
    fbase="${f##*/}"
    if [[ "$fbase" =~ ^[0-9]+\.md$ ]]; then
      v=$((10#${fbase%.md}))          # 10# keeps 08.md, 09.md from parsing as octal
      if (( v > n )); then n=$v; fi
    fi
  done
  printf '%s/%d.md' "$dir" "$((n + 1))"
}

if [[ -z "$sess" ]]; then
  for f in "$ROLLOUT_DIR"/model-io-sess_*.jsonl; do
    if [[ -f "$f" && (-z "$sess" || "$f" -nt "$sess") ]]; then sess="$f"; fi
  done
  [[ -n "$sess" ]] || { echo "error: no model-io-sess_*.jsonl found in $ROLLOUT_DIR" >&2; exit 1; }
elif [[ "$sess" != /* && "$sess" != *.jsonl ]]; then   # session id or unambiguous prefix
  exact="$ROLLOUT_DIR/model-io-$sess.jsonl"
  if [[ -f "$exact" ]]; then
    sess="$exact"
  else
    matches=("$ROLLOUT_DIR/model-io-$sess"*.jsonl)
    if (( ${#matches[@]} == 1 )) && [[ -f "${matches[0]}" ]]; then
      sess="${matches[0]}"
    else
      echo "error: no unique session matching '$sess'" >&2; exit 1
    fi
  fi
fi
if [[ "$sess" != /* ]]; then sess="$PWD/$sess"; fi
[[ -f "$sess" ]] || { echo "error: not a file: $sess" >&2; exit 1; }

if [[ -z "$out" && -n "$destdir" ]]; then
  dest="$(resolve_dest "$destdir" strict)" || { echo "error: cannot resolve destination dir: $destdir" >&2; exit 1; }
  out="$(pick_output "$dest")"; generated=1
elif [[ -z "$out" && "$session_given" -eq 0 ]]; then   # double-click mode: dest from clipboard
  clip=""
  if command -v wl-paste >/dev/null 2>&1; then
    clip="$(wl-paste --primary 2>/dev/null || true)"
    [[ -z "$clip" ]] && clip="$(wl-paste 2>/dev/null || true)"
  fi
  if [[ -n "$clip" ]] && p="$(clean_path "$clip")" && dest="$(resolve_dest "$p" clipboard)"; then
    out="$(pick_output "$dest")"; generated=1
  fi
fi
# destination-generated names must be fresh: numbered names always are, but a
# semver folder's canonical name may already exist — refuse rather than clobber
if [[ -n "${generated:-}" && -e "$out" ]]; then
  echo "error: output already exists: $out (use -o to overwrite deliberately)" >&2; exit 1
fi

if [[ -n "$out" ]]; then
  echo "transcript.sh: writing to $out" >&2
  exec >"$out"
fi

ROLLOUT_DIR="$ROLLOUT_DIR" MODEL="$MODEL" PROVIDER="$PROVIDER" HARNESS="$HARNESS" \
ATTACH_MAX_CHARS="$ATTACH_MAX_CHARS" python3 - "$sess" <<'PY'
import json, os, re, sys

path = sys.argv[1]
model_cfg = os.environ["MODEL"]
provider = os.environ["PROVIDER"]
harness = os.environ["HARNESS"]
attach_max = int(os.environ["ATTACH_MAX_CHARS"])

records = []
with open(path) as fh:
    for line in fh:
        line = line.strip()
        if not line:
            continue
        try:
            rec = json.loads(line)
        except json.JSONDecodeError:
            continue
        if rec.get("querySource") != "main_turn":
            continue
        if (rec.get("model") or {}).get("role") == "lite":
            continue
        if not rec.get("turnId") or not isinstance(rec.get("request"), dict):
            continue
        records.append(rec)
if not records:
    sys.exit("error: no main-turn model calls found in " + path)

REMINDER = re.compile(r"(?s)<system-reminder>.*?</system-reminder>\s*")
CONTINUE_ONLY = re.compile(
    r"^\s*(?:continue(?: from cutoff| from where (?:you|we) left off| working|,? please)?"
    r"|go on|keep going|[.?!]+)[.!?]*\s*$", re.I)
ATTACH = re.compile(r"(?s)Contents of (.+?)\s*\n(.*)")
IMG_EXT = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg", ".bmp")
DATA_URI = re.compile(r"!\[[^\]]*\]\(\s*data:[^)]+\)|data:(?:image|application)/[a-z+]+;base64,[A-Za-z0-9+/=]+")
# GLM server-side tool narration (web_search_prime, analyze_image, ...) is streamed
# into response.text: a call block ("🌐 ... *Executing on server...*") followed by
# "**Output:**" payload paragraphs. Both are tool activity, not agent prose.
SERVER_CALL = re.compile(r"(?s)\*\*🌐 Z\.ai Built-in Tool:[^\n]*\*\*.*?\*Executing on server\.\.\.\*\s*")
SERVER_OUT = re.compile(r"(?ms)^[ \t]*\*\*Output:\*\*[ \t]*\n(?:^[ \t]*\S.*\n)+")

def strip_server_tools(text):
    text = SERVER_CALL.sub("", text)
    text = SERVER_OUT.sub("", text)
    return re.sub(r"\n{3,}", "\n\n", text).strip()

def demote(text):
    """Shift ATX headers down so in-content headers land at ####+ (outside code fences)."""
    out_lines, fence = [], False
    for ln in text.split("\n"):
        if ln.lstrip().startswith("```"):
            fence = not fence
        m = None if fence else re.match(r"^(#{1,6})(\s+)", ln)
        if m:
            lvl = min(max(len(m.group(1)) + 2, 4), 6)
            ln = "#" * lvl + m.group(2) + ln[m.end():]
        out_lines.append(ln)
    return "\n".join(out_lines)

def user_content(msg):
    """Return (typed_text, attachment_blocks) for a user message."""
    content = msg.get("content")
    parts = content if isinstance(content, list) else [{"type": "text", "text": str(content)}]
    texts, attaches = [], []
    for p in parts:
        ptype = p.get("type", "text")
        if ptype == "text":
            raw = p.get("text", "")
        elif ptype in ("image", "file", "document"):
            name = p.get("filename") or p.get("name") or ""
            attaches.append(f"**{name or ptype + ' attachment'}:** *(content dropped)*")
            continue
        else:
            continue
        for block in REMINDER.findall(raw + "\n"):
            m = ATTACH.match(block.strip())
            if m:
                fpath, fcontent = m.group(1).strip(), m.group(2).strip()
                base = os.path.basename(fpath.rstrip("/"))
                if base.lower().endswith(IMG_EXT):
                    attaches.append(f"**{base}:** *(image attachment dropped)*")
                elif len(fcontent) > attach_max:
                    attaches.append(f"**{base}:** *(attachment dropped: {len(fcontent)} chars)*")
                else:
                    attaches.append(f"**{base}:**\n{demote(fcontent)}")
        texts.append(DATA_URI.sub("**[image attachment]**", REMINDER.sub("", raw)).strip())
    typed = "\n\n".join(t for t in texts if t)
    return typed, attaches

turns, order = {}, []
for rec in records:
    tid = rec["turnId"]
    if tid not in turns:
        turns[tid] = {"user": None, "attaches": [], "agent": []}
        order.append(tid)
    t = turns[tid]
    if t["user"] is None:
        users = [m for m in rec["request"].get("messages", []) if m.get("role") == "user"]
        for msg in reversed(users):          # last real user message wins; reminder-only ones skipped
            typed, attaches = user_content(msg)
            if typed:
                t["user"], t["attaches"] = typed, attaches
                break
    text = (rec.get("response") or {}).get("text") or ""
    if text.strip():
        t["agent"].append(strip_server_tools(text))

# drop continue-only turns, merging their agent output into the interrupted turn
merged = []
for tid in order:
    t = turns[tid]
    if t["user"] is None:
        continue
    if merged and CONTINUE_ONLY.match(t["user"]):
        merged[-1]["agent"].extend(t["agent"])
        continue
    merged.append(t)

if not merged:
    sys.exit("error: no user turns found")

model = model_cfg or next(
    ((r.get("model") or {}).get("modelId") for r in records if (r.get("model") or {}).get("modelId")),
    "unknown")

print("---")
print(f"model: {model}")
print(f"provider: {provider}")
print(f"harness: {harness}")
print("---")
for i, t in enumerate(merged, 1):
    print(f"\n## Turn {i}\n")
    print("### User:\n")
    print(demote(t["user"]))
    for a in t["attaches"]:
        print("\n" + a)
    print("\n---\n")
    print("### Agent:\n")
    body = "\n\n".join(demote(a) for a in t["agent"])
    print(body if body else "*(interrupted — no captured agent output)*")
    if i < len(merged):
        print("\n---")
PY

if [[ -n "$out" ]] && command -v notify-send >/dev/null 2>&1; then
  notify-send -a "transcript.sh" "Transcript written" "$out" 2>/dev/null || true
fi
